デザイン部分の調整
Melonps/my_terminal pull request #32
Opened 2023-04-06 09:37 UTC by Melonps

## 概要
- 現状できているコンポーネントの調整を行いました（ヘッダーフッターの非表示など）
- ルーチングの設定をしました（ルーチングは用意しているけど明示しないようにした）
- 一部レスポンシブ化しました
- 背景、メニューのUIを変更しました

2023-04-06 09:55 UTC, yiRMT approved these changes
とてもいいと思う！以下コメント

- Settingを開いた時の文字の色が見づらいかも．ブラーをかけるとしたら，Settingsのモーダル内を暗めにするとか
- なんてフォントか知らないけど，Setting内の文字が細いかも :)

2023-04-06 16:00 UTC, Melonps commented
コメントありがとう！
>Settingを開いた時の文字の色が見づらいかも．ブラーをかけるとしたら，Settingsのモーダル内を暗めにするとか

確かにそう思った！これなんだけど、背景画像によって適切な文字色も変わると思うので、後からテキストカラーとハイライトカラーを入力できるようにした方がいいと思う！

>なんてフォントか知らないけど，Setting内の文字が細いかも :)

直します

2023-04-07 04:20 UTC, yiRMT requested changes
ちょっと見づらいかも．文字に影をつけたら良さそう．

![image](https://user-images.githubusercontent.com/9864901/230540092-7953b795-0af6-4193-999b-3855e1adccff.png)

2023-04-07 07:54 UTC, Melonps commented
@yiRMT 
text-shadowはあり得ん程調整が難しんだよね。フォント太くしてみたんだけどこれでどう？
![image](https://user-images.githubusercontent.com/95263124/230567160-2dbf6c11-b0fa-4be4-9edd-00b408cfe450.png)

2023-04-07 08:59 UTC, yiRMT commented
太字にしてもあまり変わらないな。とりあえず完成させたいし、このままマージしよう。
次に自分はサインイン状態によって設定の表示／非表示を変えようと思う。

2023-04-07 09:15 UTC, merged